# Site Settings
locale                   : "en-US"
title                    : Keisuke Kwong
title_separator          : "-"
subtitle                 : # site tagline that appears below site title in masthead
name                     : Keisuke Kwong
description              : Keisuke Kwong - Projects and CV 
url                      : "https://cornell-mae-ug.github.io"
baseurl                  : "/sp26-portfolio-kk227325"

# Theme and Style
theme: jekyll-theme-cayman
color_scheme: light # light/default, dark, or aqua

sass:
  style: compressed

# Outputting
permalink: /:categories/:title/

collections:
  pages:
    output: true
  projects:
    output: true
    permalink: /:collection/:path/
  projects2:
    output: true
    permalink: /:collection/:path/

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  extensions: [smartypants, stray_backslashes, tables]

# Plugins (previously gems:)
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag

